modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Ice%20Prevents%20Crop%20Growth"
logoFile="icon.png"

[[mods]]
modId="icepreventscropgrowth"
version="3.2"
displayName="Ice Prevents Crop Growth"
displayURL="https://serilum.com/mod/ice-prevents-crop-growth"
authors="Rick South"
description='''Crops growing on tilled soil with an ice block underneath will never grow to the next stage, for design purposes.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.icepreventscropgrowth]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.icepreventscropgrowth]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "icepreventscropgrowth_neoforge.mixins.json"